<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_boost-your-income-section',
		'title' => 'Boost your income section',
		'fields' => array (
			array (
				'key' => 'field_5a77673f7e6fc',
				'label' => 'Income Feature Image',
				'name' => 'income_feature_image',
				'type' => 'image',
				'instructions' => 'Upload an image for this section',
				'save_format' => 'object',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_5a7767747e6fd',
				'label' => 'Income Section Title',
				'name' => 'income_section_title',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a7767cd7e6fe',
				'label' => 'Income Section Description',
				'name' => 'income_section_description',
				'type' => 'textarea',
				'instructions' => 'Enter a brief, but awesome, description for this section.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5a776ae5e7eaa',
				'label' => 'Reason #1',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5a7768477e6ff',
				'label' => 'Title',
				'name' => 'reason_1_title',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a7768797e700',
				'label' => 'Description',
				'name' => 'reason_1_description',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5a776b36e7eab',
				'label' => 'Reason #2',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5a7768c17e702',
				'label' => 'Title',
				'name' => 'reason_2_title',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a7768dc7e704',
				'label' => 'Description',
				'name' => 'reason_2_description',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '13',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_course-feature',
		'title' => 'Course Feature',
		'fields' => array (
			array (
				'key' => 'field_5a88b315b24f9',
				'label' => 'Course Feature Icon',
				'name' => 'course_feature_icon',
				'type' => 'radio',
				'instructions' => 'Choose the icon you\'d like to display with the feature.',
				'required' => 1,
				'choices' => array (
					'ci ci-computer' => 'Computer',
					'ci ci-watch' => 'Watch',
					'ci ci-calendar' => 'Calendar',
					'ci ci-community' => 'Community',
					'ci ci-instructor' => 'Instructor',
					'ci ci-device' => 'Device',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'course_feature',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_course-feature-section',
		'title' => 'Course Feature Section',
		'fields' => array (
			array (
				'key' => 'field_5a88b77c30546',
				'label' => 'Features Section Image',
				'name' => 'features_section_image',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_5a88b7a130547',
				'label' => 'Features Section Title',
				'name' => 'features_section_title',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a88b7c130548',
				'label' => 'Features Section Body',
				'name' => 'features_section_body',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '13',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_instructor-section',
		'title' => 'Instructor Section',
		'fields' => array (
			array (
				'key' => 'field_5a89dae5be655',
				'label' => 'Instructor Section Title',
				'name' => 'instructor_section_title',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a89db1cbe656',
				'label' => 'Instructor Name',
				'name' => 'instructor_name',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a89db37be657',
				'label' => 'Bio Excerpt',
				'name' => 'bio_excerpt',
				'type' => 'text',
				'instructions' => 'Enter a brief intro to the instructor\'s bio.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a89db6dbe658',
				'label' => 'Full Bio',
				'name' => 'full_bio',
				'type' => 'textarea',
				'instructions' => 'Enter the remainder of the instructor\'s bio.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5a89df43be65f',
				'label' => 'Social Icons',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5a89dda3be659',
				'label' => 'Twitter Username',
				'name' => 'twitter_username',
				'type' => 'text',
				'instructions' => 'Enter the instructor\'s twitter username.',
				'default_value' => '',
				'placeholder' => 'bradhussey',
				'prepend' => '@',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a89de54be65a',
				'label' => 'Facebook Username',
				'name' => 'facebook_username',
				'type' => 'text',
				'instructions' => 'Enter the instructor\'s facebook username.',
				'default_value' => '',
				'placeholder' => 'bradhussey',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a89de80be65b',
				'label' => 'Google Plus Username',
				'name' => 'google_plus_username',
				'type' => 'text',
				'instructions' => 'Enter the instructor\'s Google Plus username.',
				'default_value' => '',
				'placeholder' => '+bradhussey',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a89df5fbe660',
				'label' => 'The Numbers',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5a89ded0be65c',
				'label' => 'Number of Students',
				'name' => 'num_students',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5a89def5be65d',
				'label' => 'Number of Reviews',
				'name' => 'num_reviews',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5a89df09be65e',
				'label' => 'Number of Courses',
				'name' => 'num_courses',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '13',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_project-features-section',
		'title' => 'Project Features Section',
		'fields' => array (
			array (
				'key' => 'field_5a89cd66c4542',
				'label' => 'Project Feature Title',
				'name' => 'project_feature_title',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a89cd8fc4543',
				'label' => 'Project Feature Body',
				'name' => 'project_feature_body',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '13',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_resources',
		'title' => 'Resources',
		'fields' => array (
			array (
				'key' => 'field_5a8a170d42f6b',
				'label' => 'Resource Image',
				'name' => 'resource_image',
				'type' => 'image',
				'required' => 1,
				'save_format' => 'object',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_5a8a174342f6c',
				'label' => 'Resource URL',
				'name' => 'resource_url',
				'type' => 'text',
				'instructions' => 'Enter a valide URL for your resource.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'http://www.googl.com.br',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a8a178b42f6d',
				'label' => 'Add Button?',
				'name' => 'add_button',
				'type' => 'true_false',
				'instructions' => 'Would you like to add a button to this resource?',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_5a8a17d642f6e',
				'label' => 'Button Text',
				'name' => 'button_text',
				'type' => 'text',
				'instructions' => 'Enter the text you\'d like to appear within the button.',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5a8a178b42f6d',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'resources_itens',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_who-should-take-this-course-section',
		'title' => 'Who should take this course section',
		'fields' => array (
			array (
				'key' => 'field_5a88a8964c724',
				'label' => 'Section Image',
				'name' => 'who_feature_image',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_5a88a8624c723',
				'label' => 'Section Title',
				'name' => 'who_section_title',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a88a8d44c725',
				'label' => 'Section Body',
				'name' => 'who_section_body',
				'type' => 'wysiwyg',
				'required' => 1,
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '13',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}